export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MOVIE_ROUTE = '/movie/:movieId'
export const MAIN_ROUTE = '/'
export const LIBRARY_ROUTE = '/library'
export const PROFILE_ROUTE = '/profile'
export const PERSON_ROUTE ='/person/:personId'
export const FILM_ROUTE = '/film/:filmId'

export const API_KEY = '6BPY2WX-2RMM7RA-NZW601H-8CC689V'
export const API_URL = 'https://api.kinopoisk.dev/v1.4'