export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MOVIE_ROUTE = '/movie/:movieId'
export const MAIN_ROUTE = '/'
export const LIBRARY_ROUTE = '/library'
export const PROFILE_ROUTE = '/profile'
export const PODBORKI_ROUTE = '/podborki'
export const PERSON_ROUTE ='/person/:personId'
export const FILM_ROUTE = '/film/:filmId'
export const NOTFOUND_ROUTE = '*'

export const API_KEY = 'DZG1JGD-HK8M500-MYWW4ZX-D4Z7RYJ'
export const API_URL = 'https://api.kinopoisk.dev/v1.4'